url: http://www.jumpcu.be
baseurl:

# Site settings
title: Virtual Jump Simulator
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2F3133
  secondary: 9CC7E4
  secondary-dark: 556D7D

# Galleries
galleries:
- name: Beginnings @ Bela's
  folder: beginnings
- name: Arsenal Objekt 219
  folder: arsenal
- name: Galaabend Technik 2015
  folder: galaabend-technik-2015

# Teamleaders
teamleaders:
- name: Horst Eidenberger
  pic: horst.jpg
  position: Project Leader
  social:

- name: Bela Eckermann
  pic: bela.jpg
  position: Chief Engineer
  social:
  - title: link
    url: http://www.bela-eckermann.at/


# Team names, titles and social links
people:
- name: Juri Berlanda
  pic: juri.jpg
  position: System Developer
  social:
  - title: github
    url: http://github.com/j-be

- name: Tobias Froihofer
  pic: tobi.jpg
  position: System Developer
  social:
  - title: github
    url: http://github.com/TobiFroi

- name: Luca Maestri
  pic: luca.jpg
  position: System Developer
  social:
  - title: github
    url: http://github.com/lmaestri

- name: Jonas Engl
  pic: jonas_e.jpg
  position: System Developer
  social:

- name: Dzenan Omerovic
  pic: dzenan.jpg
  position: System Developer
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
